namespace Native.SourceGenerator.DependencyInjection.Emitters;

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Native.SourceGenerator.DependencyInjection.Models;

internal static class ServiceRegistrationEmitter
{
    public static string EmitServiceRegistrations(IEnumerable<ServiceRegistrationInfo> registrations)
    {
        var registrationsList = registrations.ToList();
        if (registrationsList.Count == 0)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Group by Group property (null means default)
        IOrderedEnumerable<IGrouping<string, ServiceRegistrationInfo>> groups = registrationsList
            .GroupBy(r => r.Group ?? string.Empty)
            .OrderBy(g => g.Key);

        // Default group (no Group specified)
        IGrouping<string, ServiceRegistrationInfo>? defaultGroup = groups.FirstOrDefault(g => g.Key == string.Empty);
        if (defaultGroup is not null)
        {
            EmitExtensionClass(sb, "NativeGeneratedServices", "AddGeneratedServices", defaultGroup);
        }

        // Named groups
        foreach (IGrouping<string, ServiceRegistrationInfo>? group in groups.Where(g => g.Key != string.Empty))
        {
            sb.AppendLine();
            var className = $"NativeGenerated{group.Key}Services";
            var methodName = $"Add{group.Key}";
            EmitExtensionClass(sb, className, methodName, group);
        }

        return sb.ToString();
    }

    private static void EmitExtensionClass(
        StringBuilder sb,
        string className,
        string methodName,
        IEnumerable<ServiceRegistrationInfo> registrations)
    {
        sb.AppendLine("namespace Native.SourceGenerator.DependencyInjection.Generated");
        sb.AppendLine("{");
        sb.Append("    public static class ");
        sb.AppendLine(className);
        sb.AppendLine("    {");

        // Extension method
        sb.Append("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ");
        sb.Append(methodName);
        sb.AppendLine("(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (ServiceRegistrationInfo registration in registrations)
        {
            EmitServiceRegistration(sb, registration);
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitServiceRegistration(StringBuilder sb, ServiceRegistrationInfo registration)
    {
        // Use fully qualified static method call instead of extension method syntax
        sb.Append("            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.Add");
        sb.Append(registration.Lifetime);
        sb.Append('<');

        if (registration.FullyQualifiedServiceTypeName is not null)
        {
            sb.Append(registration.FullyQualifiedServiceTypeName);
            sb.Append(", ");
        }

        sb.Append(registration.FullyQualifiedClassName);
        sb.AppendLine(">(services);");
    }
}
