namespace Native.SourceGenerator.Configuration;

using System.Linq;
using Microsoft.CodeAnalysis;
using Native.SourceGenerator.Configuration.Emitters;
using Native.SourceGenerator.Configuration.Parsing;

/// <summary>
/// Incremental source generator for AOT-compatible configuration binding.
/// Generates code to read environment variables without ConfigurationBinder or reflection.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ConfigurationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register attribute source
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("EnvironmentConfigAttribute.g.cs", GetEnvironmentConfigAttributeSource());
        });

        // Find all classes with fields marked with [EnvironmentConfig]
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, ct) => ConfigurationParser.HasEnvironmentConfigFields(node, ct),
                transform: static (ctx, ct) => ConfigurationParser.ParseConfigurationClass(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        // Generate configuration injection method for each class
        context.RegisterSourceOutput(classDeclarations, static (ctx, info) =>
        {
            var source = ConfigurationEmitter.EmitConfigurationInjection(info);
            if (!string.IsNullOrEmpty(source))
            {
                ctx.AddSource($"{info.ClassName}.Configuration.g.cs", source);
            }
        });
    }

    private static string GetEnvironmentConfigAttributeSource() => """
        // <auto-generated />
        #nullable enable

        namespace Native.SourceGenerator.Configuration
        {
            /// <summary>
            /// Marks a field to be populated from an environment variable.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
            internal sealed class EnvironmentConfigAttribute : global::System.Attribute
            {
                /// <summary>
                /// The name of the environment variable.
                /// </summary>
                public string EnvironmentVariableName { get; }

                /// <summary>
                /// Whether the configuration is required. Defaults to true.
                /// </summary>
                public bool Required { get; set; } = true;

                /// <summary>
                /// The default value if the environment variable is not set.
                /// </summary>
                public string? DefaultValue { get; set; }

                /// <summary>
                /// Creates a new EnvironmentConfigAttribute.
                /// </summary>
                /// <param name="environmentVariableName">The name of the environment variable.</param>
                public EnvironmentConfigAttribute(string environmentVariableName)
                {
                    EnvironmentVariableName = environmentVariableName;
                }
            }
        }
        """;
}
