// <auto-generated />
// Required for record types in netstandard2.0

#if NETSTANDARD2_0 || NETSTANDARD2_1 || NET461_OR_GREATER || NET471_OR_GREATER || NET48_OR_GREATER

namespace System.Runtime.CompilerServices
{
    using System.ComponentModel;

    /// <summary>
    /// Reserved to be used by the compiler for tracking metadata.
    /// This class should not be used by developers in source code.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal static class IsExternalInit
    {
    }
}

#endif
