namespace NativeFluentValidator.SourceGenerator.DependencyInjection.Emitters;

using System.Text;
using NativeFluentValidator.SourceGenerator.DependencyInjection.Models;

internal static class ValidatorConstructorEmitter
{
    public static string EmitConstructor(ValidatorRegistrationInfo info)
    {
        if (info.InjectableFields.IsEmpty)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.Append("namespace ");
            sb.AppendLine(info.Namespace);
            sb.AppendLine("{");
        }

        // Class declaration
        var indent = string.IsNullOrEmpty(info.Namespace) ? "" : "    ";
        sb.Append(indent);
        sb.Append("partial class ");
        sb.AppendLine(info.ClassName);
        sb.Append(indent);
        sb.AppendLine("{");

        // Constructor
        EmitConstructorBody(sb, info, indent);

        // Close class
        sb.Append(indent);
        sb.AppendLine("}");

        // Close namespace
        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void EmitConstructorBody(StringBuilder sb, ValidatorRegistrationInfo info, string classIndent)
    {
        var memberIndent = classIndent + "    ";
        var bodyIndent = memberIndent + "    ";

        // Constructor signature
        sb.Append(memberIndent);
        sb.Append("public ");
        sb.Append(info.ClassName);
        sb.AppendLine("(");

        // Parameters
        for (var i = 0; i < info.InjectableFields.Length; i++)
        {
            var field = info.InjectableFields[i];
            sb.Append(bodyIndent);
            sb.Append(field.FullyQualifiedFieldType);
            sb.Append(' ');
            sb.Append(field.ParameterName);

            if (i < info.InjectableFields.Length - 1)
            {
                sb.AppendLine(",");
            }
            else
            {
                sb.AppendLine(")");
            }
        }

        // Constructor body
        sb.Append(memberIndent);
        sb.AppendLine("{");

        foreach (var field in info.InjectableFields)
        {
            sb.Append(bodyIndent);
            sb.Append(field.FieldName);
            sb.Append(" = ");
            sb.Append(field.ParameterName);
            sb.AppendLine(";");
        }

        sb.Append(memberIndent);
        sb.AppendLine("}");
    }
}
