namespace NativeFluentValidator.SourceGenerator.DependencyInjection.Emitters;

using System.Collections.Generic;
using System.Linq;
using System.Text;
using NativeFluentValidator.SourceGenerator.DependencyInjection.Models;

internal static class ValidatorRegistrationEmitter
{
    public static string EmitValidatorRegistrations(IEnumerable<ValidatorRegistrationInfo> registrations)
    {
        var registrationsList = registrations.ToList();
        if (registrationsList.Count == 0)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Extension methods for registering NativeFluentValidators.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class NativeFluentValidatorServicesExtensions");
        sb.AppendLine("    {");

        // Main method that adds all validators
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Adds all generated NativeFluentValidators to the service collection.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddNativeFluentValidators(");
        sb.AppendLine("            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var registration in registrationsList)
        {
            EmitValidatorRegistration(sb, registration);
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");

        // Group by Group property for grouped methods
        var groups = registrationsList
            .Where(r => r.Group != null)
            .GroupBy(r => r.Group!)
            .OrderBy(g => g.Key);

        foreach (var group in groups)
        {
            sb.AppendLine();
            EmitGroupMethod(sb, group.Key, group);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitGroupMethod(
        StringBuilder sb,
        string groupName,
        IEnumerable<ValidatorRegistrationInfo> registrations)
    {
        var methodName = $"Add{groupName}";

        sb.AppendLine("        /// <summary>");
        sb.Append("        /// Adds validators from group '");
        sb.Append(groupName);
        sb.AppendLine("' to the service collection.");
        sb.AppendLine("        /// </summary>");
        sb.Append("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ");
        sb.Append(methodName);
        sb.AppendLine("(");
        sb.AppendLine("            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var registration in registrations)
        {
            EmitValidatorRegistration(sb, registration);
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
    }

    private static void EmitValidatorRegistration(StringBuilder sb, ValidatorRegistrationInfo registration)
    {
        // Register validator with appropriate lifetime
        sb.Append("            services.Add");
        sb.Append(registration.Lifetime);
        sb.Append("<");
        sb.Append(registration.FullyQualifiedClassName);
        sb.AppendLine(">();");
    }
}
