namespace Native.SourceGenerator.Configuration.Emitters;

using System.Text;
using Native.SourceGenerator.Configuration.Models;

internal static class ConfigurationEmitter
{
    public static string EmitConfigurationInjection(ConfigurationClassInfo info)
    {
        if (info.Fields.IsEmpty)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.Append("namespace ");
            sb.AppendLine(info.Namespace);
            sb.AppendLine("{");
        }

        // Class declaration
        var indent = string.IsNullOrEmpty(info.Namespace) ? "" : "    ";
        sb.Append(indent);
        sb.Append("partial class ");
        sb.AppendLine(info.ClassName);
        sb.Append(indent);
        sb.AppendLine("{");

        // __InjectConfiguration method
        EmitInjectConfigurationMethod(sb, info, indent);

        // Close class
        sb.Append(indent);
        sb.AppendLine("}");

        // Close namespace
        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void EmitInjectConfigurationMethod(StringBuilder sb, ConfigurationClassInfo info, string classIndent)
    {
        var memberIndent = classIndent + "    ";
        var bodyIndent = memberIndent + "    ";

        sb.Append(memberIndent);
        sb.AppendLine("/// <summary>");
        sb.Append(memberIndent);
        sb.AppendLine("/// Injects configuration values from the provided IConfiguration instance.");
        sb.Append(memberIndent);
        sb.AppendLine("/// </summary>");
        sb.Append(memberIndent);
        sb.AppendLine("public void __InjectConfiguration(global::Microsoft.Extensions.Configuration.IConfiguration configuration)");
        sb.Append(memberIndent);
        sb.AppendLine("{");

        foreach (ConfigurationFieldInfo field in info.Fields)
        {
            EmitFieldAssignment(sb, field, bodyIndent);
        }

        sb.Append(memberIndent);
        sb.AppendLine("}");
    }

    private static void EmitFieldAssignment(StringBuilder sb, ConfigurationFieldInfo field, string indent)
    {
        var configAccess = $"configuration[\"{field.ConfigurationKey}\"]";

        // Determine if the type is nullable
        var isNullableType = field.FullyQualifiedFieldType.EndsWith("?");
        var baseType = isNullableType
            ? field.FullyQualifiedFieldType.TrimEnd('?')
            : field.FullyQualifiedFieldType;

        sb.Append(indent);
        sb.Append(field.FieldName);
        sb.AppendLine(" =");

        // Handle different types
        if (baseType is "string" or "global::System.String")
        {
            EmitStringAssignment(sb, field, indent, configAccess);
        }
        else if (baseType is "int" or "global::System.Int32")
        {
            EmitParsableAssignment(sb, field, indent, configAccess, "int", "0");
        }
        else if (baseType is "long" or "global::System.Int64")
        {
            EmitParsableAssignment(sb, field, indent, configAccess, "long", "0L");
        }
        else if (baseType is "bool" or "global::System.Boolean")
        {
            EmitParsableAssignment(sb, field, indent, configAccess, "bool", "false");
        }
        else if (baseType is "double" or "global::System.Double")
        {
            EmitParsableAssignment(sb, field, indent, configAccess, "double", "0.0");
        }
        else if (baseType is "decimal" or "global::System.Decimal")
        {
            EmitParsableAssignment(sb, field, indent, configAccess, "decimal", "0m");
        }
        else if (baseType is "global::System.TimeSpan")
        {
            EmitTimeSpanAssignment(sb, field, indent, configAccess);
        }
        else if (baseType is "global::System.Uri")
        {
            EmitUriAssignment(sb, field, indent, configAccess);
        }
        else
        {
            // Fallback to string for unknown types
            EmitStringAssignment(sb, field, indent, configAccess);
        }

        sb.AppendLine();
    }

    private static void EmitStringAssignment(StringBuilder sb, ConfigurationFieldInfo field, string indent, string configAccess)
    {
        sb.Append(indent);
        sb.Append("    ");
        sb.Append(configAccess);

        if (field.IsRequired && field.DefaultValue is null)
        {
            sb.AppendLine();
            sb.Append(indent);
            sb.Append("    ?? throw new global::System.InvalidOperationException(\"Missing required configuration: ");
            sb.Append(field.ConfigurationKey);
            sb.Append("\");");
        }
        else if (field.DefaultValue is not null)
        {
            sb.Append(" ?? \"");
            sb.Append(field.DefaultValue);
            sb.Append("\";");
        }
        else
        {
            sb.Append(';');
        }
    }

    private static void EmitParsableAssignment(
        StringBuilder sb,
        ConfigurationFieldInfo field,
        string indent,
        string configAccess,
        string typeName,
        string defaultLiteral)
    {
        // configuration["NAME"] is { Length: > 0 } __fieldValue
        //     ? type.Parse(__fieldValue)
        //     : default/throw
        sb.Append(indent);
        sb.Append("    ");
        sb.Append(configAccess);
        sb.Append(" is { Length: > 0 } __");
        sb.Append(field.FieldName);
        sb.AppendLine("Value");
        sb.Append(indent);
        sb.Append("        ? ");
        sb.Append(typeName);
        sb.Append(".Parse(__");
        sb.Append(field.FieldName);
        sb.AppendLine("Value)");
        sb.Append(indent);
        sb.Append("        : ");

        if (field.IsRequired && field.DefaultValue is null)
        {
            sb.Append("throw new global::System.InvalidOperationException(\"Missing required configuration: ");
            sb.Append(field.ConfigurationKey);
            sb.Append("\");");
        }
        else if (field.DefaultValue is not null)
        {
            sb.Append(typeName);
            sb.Append(".Parse(\"");
            sb.Append(field.DefaultValue);
            sb.Append("\");");
        }
        else
        {
            sb.Append(defaultLiteral);
            sb.Append(';');
        }
    }

    private static void EmitTimeSpanAssignment(StringBuilder sb, ConfigurationFieldInfo field, string indent, string configAccess)
    {
        sb.Append(indent);
        sb.Append("    ");
        sb.Append(configAccess);
        sb.Append(" is { Length: > 0 } __");
        sb.Append(field.FieldName);
        sb.AppendLine("Value");
        sb.Append(indent);
        sb.Append("        ? global::System.TimeSpan.Parse(__");
        sb.Append(field.FieldName);
        sb.AppendLine("Value)");
        sb.Append(indent);
        sb.Append("        : ");

        if (field.IsRequired && field.DefaultValue is null)
        {
            sb.Append("throw new global::System.InvalidOperationException(\"Missing required configuration: ");
            sb.Append(field.ConfigurationKey);
            sb.Append("\");");
        }
        else if (field.DefaultValue is not null)
        {
            sb.Append("global::System.TimeSpan.Parse(\"");
            sb.Append(field.DefaultValue);
            sb.Append("\");");
        }
        else
        {
            sb.Append("global::System.TimeSpan.Zero;");
        }
    }

    private static void EmitUriAssignment(StringBuilder sb, ConfigurationFieldInfo field, string indent, string configAccess)
    {
        sb.Append(indent);
        sb.Append("    ");
        sb.Append(configAccess);
        sb.Append(" is { Length: > 0 } __");
        sb.Append(field.FieldName);
        sb.AppendLine("Value");
        sb.Append(indent);
        sb.Append("        ? new global::System.Uri(__");
        sb.Append(field.FieldName);
        sb.AppendLine("Value)");
        sb.Append(indent);
        sb.Append("        : ");

        if (field.IsRequired && field.DefaultValue is null)
        {
            sb.Append("throw new global::System.InvalidOperationException(\"Missing required configuration: ");
            sb.Append(field.ConfigurationKey);
            sb.Append("\");");
        }
        else if (field.DefaultValue is not null)
        {
            sb.Append("new global::System.Uri(\"");
            sb.Append(field.DefaultValue);
            sb.Append("\");");
        }
        else
        {
            sb.Append("null!;");
        }
    }
}
