namespace NativeFluentValidator.SourceGenerator.DependencyInjection.Attributes;

/// <summary>
/// Contains the source code for the NativeValidator attribute.
/// </summary>
internal static class ValidatorAttributes
{
    public const string NativeValidatorAttributeSource = """
        // <auto-generated />
        #nullable enable

        namespace NativeFluentValidator.SourceGenerator.DependencyInjection
        {
            /// <summary>
            /// Marks a class as a NativeFluentValidator for AOT-compatible registration.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            [global::System.Diagnostics.Conditional("NATIVE_VALIDATOR_GENERATOR")]
            internal sealed class NativeValidatorAttribute : global::System.Attribute
            {
                /// <summary>
                /// Gets or sets the service lifetime. Default is Scoped.
                /// </summary>
                public ServiceLifetime Lifetime { get; set; } = ServiceLifetime.Scoped;

                /// <summary>
                /// Gets or sets the registration group name for grouped extensions.
                /// </summary>
                public string? Group { get; set; }
            }

            /// <summary>
            /// Specifies the service lifetime for validators.
            /// </summary>
            internal enum ServiceLifetime
            {
                Singleton = 0,
                Scoped = 1,
                Transient = 2
            }
        }
        """;
}
